export const POSITIVE_OFFER = ' POSITIVE_OFFER';
export const NEGATIVE_OFFER = 'NEGATIVE_OFFER';

export const INITIAL_CYCLE_DATA = 'INITIAL_CYCLE_DATA';
export const UPDATE_PERIOD_DAYS = 'UPDATE_PERIOD_DAYS';
export const SET_LAST_PERIOD_DATE = 'SET_LAST_PERIOD_DATE';
export const SET_PREGNANT_MODE = 'SET_PREGNANT_MODE';

export const SET_MODE = 'SET_MODE';

export const SET_MAIN_SENTENCE = 'SET_MAIN_SENTENCE';
