import { StyleSheet } from 'react-native';
import { COLOR, SIZE, FONT, WIDTH, HEIGHT } from '../../styles/static';

export default StyleSheet.create({
  container: {
    backgroundColor: COLOR.bgColor,
    flex: 1,
  },
  button: {
    alignSelf: 'center',
    bottom: -30,
    position: 'absolute',
  },
  close: {
    position: 'absolute',
    top: 15,
    left: 15,
  },
  error: {
    fontSize: 12,
    color: 'red',
    alignSelf: 'center',
  },
  BTNStyle: {
    backgroundColor: 'white',
    marginVertical: 5,
    borderRadius: 40,
    width: WIDTH * 0.9,
    height: HEIGHT * 0.094,
    elevation: 2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  TextBTNStyle: {
    fontFamily: FONT.medium,
    fontSize: SIZE[14],
    color: COLOR.textColor,
    marginBottom: 10,
  },
  TextBTNStyle1: {
    fontFamily: FONT.light,
    fontSize: SIZE[12],
    color: COLOR.textColor,
  },
  imgbackground1: {
    width: (HEIGHT * 0.27) / 0.72,
    height: HEIGHT * 0.27,
    alignSelf: 'flex-end',
  },
  viq1: {
    position: 'absolute',
    alignSelf: 'center',
    top: HEIGHT * 0.16,
  },
  txtTop: {
    fontFamily: FONT.medium,
    fontSize: SIZE[14],
    textAlign: 'center',
    color: COLOR.textColor,
  },
  viewbtnsq1: {
    position: 'absolute',
    height: HEIGHT * 0.32,
    width: WIDTH * 1,
    top: HEIGHT * 0.4,
    alignItems: 'center',
    justifyContent: 'center',
  },
  imgendq1: {
    width: (HEIGHT * 0.2) / 0.4,
    height: HEIGHT * 0.2,
    position: 'absolute',
    bottom: 0,
    left: -91,
  },
  img1q2: {
    width: WIDTH * 1.22,
    height: HEIGHT * 0.8,
    position: 'absolute',
  },
  v1q2: {
    position: 'absolute',
    width: '100%',
    height: '100%',
  },
  v2q2: {
    flex: 0.5,
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  v3q3: {
    width: '80%',
    height: '30%',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  parentView: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  stepper: {
    width: WIDTH * 0.083,
    height: HEIGHT * 0.008,
    backgroundColor: COLOR.nextPage,
    borderRadius: 50,
    marginHorizontal: 5,
  },
  v4q2: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  v5q2: {
    width: '85%',
    height: '90%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  textq2: {
    alignSelf: 'center',
    fontSize: SIZE[16],
    fontFamily: FONT.medium,
    marginTop: 7,
    opacity: 0.7,
  },
  v6q2: {
    flex: 2.2,
    justifyContent: 'center',
    alignItems: 'center',
  },
  v7q2: {
    width: '90%',
    height: '95%',
    elevation: 0,
  },
  viewforget: {
    flex: 1.5,
    justifyContent: 'center',
    alignItems: 'center',
  },
  txtforget: {
    fontFamily: FONT.regular,
    fontSize: SIZE[17],
    textDecorationLine: 'underline',
    opacity: 0.7,
  },
  btnsview: {
    flex: 1.2,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
  },
  btnback: {
    height: '40%',
    width: '80%',
    backgroundColor: 'white',
    borderRadius: 40,
    elevation: 3,
    justifyContent: 'center',
    alignItems: 'center',
  },
  txtbtn: {
    fontFamily: FONT.regular,
    fontSize: 14,
  },
  textStyle: {
    alignSelf: 'center',
    fontSize: SIZE[14],
    fontFamily: FONT.medium,
    marginTop: 7,
    opacity: 0.7,
  },
  textStyle1: {
    alignSelf: 'center',
    fontSize: SIZE[17],
    fontFamily: FONT.medium,
    marginTop: 3,
    opacity: 0.7,
  },
  textStyle2: {
    alignSelf: 'center',
    fontSize: SIZE[14],
    fontFamily: FONT.regular,
    marginTop: 10,
    opacity: 0.5,
  },
});
