import { StyleSheet } from 'react-native';
import { WIDTH, FONT, SIZE, COLOR } from '../../styles/static';

export default StyleSheet.create({
  screen: {
    padding: 8,
    alignItems: 'center',
    alignContent: 'center',
    height: '95%',
    width: '95%',
    alignSelf: 'center',
  },
  up: {
    flexDirection: 'row',
    alignContent: 'center',
    justifyContent: 'center',
    marginTop: 2,
  },
  design: {
    alignContent: 'center',
    alignItems: 'center',
  },
  all: {
    width: '90%',
    flexDirection: 'row',
  },
  all2: {
    width: '60%',
    flexDirection: 'row',
  },
  text1: {
    width: '80%',
    padding: 8,
    fontSize: 26,
    alignItems: 'center',
    textAlign: 'center',
    fontFamily: 'B Karim',
  },
  text2: {
    width: '80%',
    fontSize: 20,
    padding: 8,
    alignItems: 'center',
    textAlign: 'center',
    fontFamily: 'B Karim',
  },
  button2: {
    width: 170,
    height: 90,
    marginTop: 6,
    paddingTop: 5,
    paddingBottom: 5,
    marginLeft: 15,
    marginRight: 15,
    fontFamily: 'B Karim',
    alignItems: 'center',
    justifyContent: 'center',
  },
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  Touch: {
    width: '90%',
    flexDirection: 'row',
    alignContent: 'center',
    justifyContent: 'center',
  },
  text3: {
    marginBottom: 1,
    marginTop: 1,
    marginLeft: 2.5,
    marginRight: 2.5,
    width: '80%',
    fontSize: 20,
    alignContent: 'space-between',
    alignItems: 'center',
    textAlign: 'center',
    alignSelf: 'center',
    fontFamily: 'B Karim',
    color: 'black',
  },
  texting: {
    fontSize: 11,
    marginTop: 3,
    marginBottom: 3,
    marginRight: 1,
    marginLeft: 1,
    padding: 9,
    borderWidth: 1,
    borderRadius: 20,
    width: '80%',
    alignItems: 'center',
    alignContent: 'space-between',
    borderColor: '#FF488A',
    color: 'black',
    textAlign: 'center',
    alignSelf: 'center',
    fontFamily: 'B Karim',
  },
  line: {
    marginBottom: 3,
  },
  allR: {
    width: '90%',
    flexDirection: 'row',
    // marginLeft: 0.5,
    // marginRight: 0.5,
    textAlign: 'center',
    alignContent: 'center',
    alignItems: 'center',
    justifyContent: 'center',
  },
  button: {
    padding: 5,
    marginBottom: 4,
    flexDirection: 'row',
    width: 30,
    height: 30,
    alignContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    textAlign: 'center',
    justifyContent: 'center',
    fontFamily: 'B Karim',
  },
});
