import { StyleSheet } from 'react-native';
import { COLOR, FONT } from '../../styles/static';

export default StyleSheet.create({
  safeAreaView: {
    flex: 1,
    paddingBottom: 50,
  },
  headerCotainer: {
    flex: 1,
    paddingHorizontal: 5,
    flexDirection: 'row-reverse',
    justifyContent: 'space-between',
    backgroundColor: 'white',
  },
  headerWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    marginTop: 20,
    width: '95%',
  },
  headerText: {
    alignSelf: 'flex-end',
    color: 'black',
    fontSize: 17,
    fontFamily: FONT.medium,
  },
  titleStyle: {
    flex: 1,
    color: 'white',
    padding: 10,
    margin: 20,
    fontSize: 20,
    backgroundColor: 'rgba(0,0,0,0.6)',
    textAlign: 'right',
    fontFamily: FONT.medium,
  },
  icon: { fontSize: 18, color: 'black', padding: 10 },
  imageHeader: {
    marginTop: 75,
    resizeMode: 'cover',
    flex: 1,
  },
  headerTitleWrapper: {
    backgroundColor: 'transparent',
    flex: 1,
    justifyContent: 'flex-end',
    alignItems: 'flex-end',
    flexDirection: 'row',
  },
  logosWrapper: {
    width: '80%',
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    alignItems: 'center',
    alignSelf: 'center',
    paddingBottom: 50,
  },
  img: {
    width: 90,
    height: 90,
    borderRadius: 20,
  },
  HTML: { width: '100%' },
  contentContiner: {
    padding: 10,
    flex: 1,
  },
  main: {
    paddingBottom: 50,
    paddingTop: 24,
  },
  button: {
    backgroundColor: '#f9d1de',
    alignItems: 'flex-end',
    alignSelf: 'center',
    width: '90%',
    padding: '5%',
    margin: 5,
    borderRadius: 15,
  },
  buttonContent: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  txt: {
    flex: 0.95,
    fontSize: 14,
    fontFamily: FONT.medium,
    paddingHorizontal: '5%',
  },
  dropIcon: {
    fontSize: 30,
    color: COLOR.btn,
  },
  GridViewContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    height: 150,
    margin: 10,
    marginTop: 20,
    backgroundColor: '#fff',
    borderRadius: 15,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.27,
    shadowRadius: 4.65,
    elevation: 6,
  },
  GridViewTextLayout: {
    fontSize: 15,
    fontFamily: FONT.medium,
    justifyContent: 'center',
    color: 'black',
    padding: 10,
    textAlign: 'center',
  },
});
